# add the following to _config.yml file
title: [Francisco Moya]
description: [Data Scientist | Data Analyst | ML/ DL | NLP | Computer Vision]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one